version: '3.8'

services:
    backend:
      image: backend
      build: ./example-backend
      ports:
        - 8080
      environment:
        - REDIS_HOST=redis_db
        - POSTGRES_HOST=postgres_db
      depends_on:
        - postgres_db
      networks:
        - fullstack-network
    redis_db:
      image: redis:alpine
      restart: unless-stopped
      networks:
        - fullstack-network
    frontend:
      image: frontend
      build: ./example-frontend
      ports:
        - 5000
      networks:
        - fullstack-network
    postgres_db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DATABASE: postgres
      volumes:
        - ./database:/var/lib/postgresql/data
      networks:
        - fullstack-network
    proxy:
      image: nginx:stable-alpine3.17
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
      networks:
        - fullstack-network
volumes:
  database:
networks:
  fullstack-network: