version: '3.8'

services:
    simple-web-service:
      image: devopsdockeruh/simple-web-service:alpine
      build: .
      ports:
        - 8000:8080
      command: ["server"]
      container_name: simple-web-service