version: '3.8'

services:
    backend:
      image: backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis_db
        - POSTGRES_HOST=postgres_db
      depends_on:
        - postgres_db
    redis_db:
      image: redis:alpine
      restart: unless-stopped
    frontend:
      image: frontend
      ports:
        - 5000:5000
    postgres_db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DATABASE: postgres
      volumes:
        - ./database:/var/lib/postgresql/data
volumes:
  database: