version: '3.8'

services:
    backend:
      image: backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis_db
    redis_db:
      image: redis:alpine
      restart: unless-stopped
    frontend:
      image: frontend
      ports:
        - 5000:5000